### ISSUE TITLE
The current version of Textual complains that this theme is out of date

### ISSUE THREAD

**Issue by sethfowler** [Xorcode/textual-solarized-dark#2]
Apparently it will stop working soon. It's already not too pleasant to use since Textual displays a huge warning message constantly while you use it.

**Comment by chrisjohnston** [comment]
I'm seeing this with Textual 5

**Comment by tbjers** [comment]
I haven't had a chance to update this to 5 yet. I'll see if I can't get
around to it soon. Need to purchase Textual 5 and get cracking. Or, I'd
very much appreciate a pull request!

**Comment by justinmrkva** [comment]
I do plan to update my fork for Textual 5, I just haven't had the time yet. I'll make a pull request when I do unless someone else beats me to it.

**Comment by tbjers** [comment]
Thank you kindly.

**Comment by tbjers** [comment]
I have merged the pull request into master. Thank you.
